"""add question created_at

Revision ID: 997cec13b8b0
Revises: c2398a3093df
Create Date: 2026-04-08 20:06:16.363506
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '997cec13b8b0'
down_revision = 'c2398a3093df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###

