"""add question reference_answer

Revision ID: e8412cd6183e
Revises: 34b37230d913
Create Date: 2026-04-08 21:34:26.731046
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e8412cd6183e'
down_revision = '34b37230d913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('reference_answer', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'reference_answer')
    # ### end Alembic commands ###

